// Login markup preserved from the confirmed V4 prototype.
export const LOGIN_HTML = "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>自动化流程监控 - 登录</title>\n<style>\n*{box-sizing:border-box}\nbody{\n  margin:0;min-height:100vh;display:grid;place-items:center;\n  font-family:Inter,\"PingFang SC\",\"Microsoft YaHei\",sans-serif;\n  background:#07111f;color:#e5e7eb\n}\n.card{\n  width:min(420px,calc(100% - 32px));background:#111827;\n  border:1px solid #243244;border-radius:16px;padding:28px\n}\nh1{margin:0 0 8px;font-size:22px}\n.sub{color:#94a3b8;font-size:13px;line-height:1.7;margin-bottom:20px}\nlabel{display:block;font-size:13px;color:#cbd5e1;margin-bottom:7px}\ninput{\n  width:100%;padding:12px 13px;border-radius:9px;border:1px solid #374151;\n  background:#0f172a;color:#fff;font-size:16px;outline:none\n}\ninput:focus{border-color:#2563eb}\nbutton{\n  width:100%;margin-top:12px;padding:12px;border:0;border-radius:9px;\n  background:#2563eb;color:#fff;font-size:15px;font-weight:700;cursor:pointer\n}\n.error{\n  margin:0 0 14px;padding:9px 10px;border-radius:8px;\n  background:#3f1518;color:#fecaca;font-size:12px\n}\n.foot{margin-top:15px;color:#64748b;font-size:11px;line-height:1.6}\n</style>\n<link rel=\"icon\" href=\"/favicon.svg\" type=\"image/svg+xml\">\n</head>\n<body>\n<div class=\"card\">\n  <h1>自动化流程监控</h1>\n  <div class=\"sub\">输入访问密码后进入监控界面。当前版本使用模拟数据，适合演示项目进度。</div>\n  __ERROR__\n  <form method=\"post\" action=\"/login\">\n    <label for=\"password\">访问密码</label>\n    <input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" autofocus required>\n    <button type=\"submit\">进入系统</button>\n  </form>\n  <div class=\"foot\">正式接入券商真实数据前，建议改为公司内网 / VPN / SSO，而不是直接公网暴露。</div>\n</div>\n</body>\n</html>";

export function loginHtml(message = "") {
  const escaped = message.replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]!));
  return LOGIN_HTML.replace("__ERROR__", message ? `<div class="error" role="alert">${escaped}</div>` : "");
}
